import React from "react";

const allWorkoutBuilderData = [
  {
    workoutbuilderId: 1011,
    filename: "treadmill-natural-time",
    type: "treadmill",
    powrOrNot: "natural",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,

          functionMode: "push",
          speed: 2,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1038,
    filename: "treadmill-natural-time2",
    type: "treadmill",
    powrOrNot: "powr",
    order: "2",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1700",
  },
  {
    workoutbuilderId: 1022,
    filename: "treadmill-powr-time",
    type: "treadmill",
    powrOrNot: "powr",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1003,
    filename: "stepper-natural-time",
    type: "stepper",
    powrOrNot: "natural",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1004,
    filename: "stepper-powr-time",
    type: "stepper",
    powrOrNot: "powr",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1005,
    filename: "rower-natural-time",
    type: "rower",
    powrOrNot: "natural",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1006,
    filename: "rower-powr-time",
    type: "rower",
    powrOrNot: "powr",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1007,
    filename: "crossTrainer-natural-time",
    type: "crossTrainer",
    powrOrNot: "natural",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1008,
    filename: "crossTrainer-powr-time",
    type: "crossTrainer",
    powrOrNot: "powr",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1009,
    filename: "cycle-natural-time",
    type: "cycle",
    powrOrNot: "natural",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1010,
    filename: "cycle-powr-time",
    type: "cycle",
    powrOrNot: "powr",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],
    totalValue: "1800",
  },
  {
    workoutbuilderId: 1011,
    filename: "elliptical-natural-time",
    type: "elliptical",
    powrOrNot: "natural",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",
        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",
        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",
        programInfo: {
          count: 2,
        },
      },
    ],

    totalValue: "1800",
  },
  {
    workoutbuilderId: 1012,
    filename: "elliptical-powr-time",
    type: "elliptical",
    powrOrNot: "powr",
    order: "1",
    program_type: "time",
    phaseinfo: [
      {
        programId: "uuid-1",
        order: "1",
        program_type: "time",

        programInfo: {
          name: "Time_P1",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-2",
        order: "2",
        program_type: "time",

        programInfo: {
          name: "Time_P2",
          totalValue: 1800,
          duration_min: 30,
          duration_sec: 0,
          incline: 0,
          speed: 4.007157,
        },
      },
      {
        programId: "uuid-3",
        order: "3",
        program_type: "loop",

        programInfo: {
          name: "Loop_P1",
          count: 2,
        },
      },
    ],

    totalValue: "1800",
  },
];
export default allWorkoutBuilderData;
